### PR TITLE
Reflex platform 21.05

### PR DESCRIPTION
**Pull request by chrbauer**
###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### CODE REVIEW

**Comment by chrbauer** [comment]
Without this ghc 8.10.7 cannot be built

**Comment by Ericson2314** [comment]
It seems odd this would be necessary when upstream Nixpkgs 21.05 is also using GHC 8.10.7 if I understand correctly?

**Comment by chrbauer** [comment]
I had the same thought: I cannot be the first one, who runs into this problem. Maybe something is wrong on this branch or repo, but i checked, that in the original 21.05 branch for NixOS the version of happy is also 1.20.

When I use your pull request on reflex-platform and i try to build an android release app, nix-build stops with a build error in the configure step. So I tried to find a solution.

I'm using nixos 22.05, which has a newer nix version (2.8.1).

**Comment by ali-abrar** [comment]
If we do need these overrides, I'd prefer they be done in reflex-platform if possible, to keep as many of the overrides as we can together and make future upgrades a bit easier.

**Comment by chrbauer** [comment]
I agree that it should be done with overrides. But I still have problems to build my app because of version mismatches of some haskell libraries like patch, ref-th, witherable, constraints, ...

Maybe we should try to go directly to nixpkgs-21.11 or nixpkgs-22.05?

**Comment by chrbauer** [comment]
I started with the overrides & nixpkgs 21.11 here: https://github.com/reflex-frp/reflex-platform/pull/783
And I close this pull request

**Comment by chrbauer** [comment]
The build of ghc fails, because of a similar error like   https://gitlab.haskell.org/ghc/ghc/-/issues/19962
I think a god fix would be to disable the generation of the ghc user manual. There is a flag (enableDocs in https://github.com/NixOS/nixpkgs/blob/release-21.11/pkgs/development/compilers/ghc/8.10.7.nix) but there is no way to overwrite it.

**Pull request closed without merging**
